task: detection

num_classes: 2
remap_mscoco_category: False

train_dataloader: 
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: ./data/so/train2017
    ann_file: ./data/so/annotations/instances_train2017.json
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  batch_size: 2
  num_workers: 4
  drop_last: True


val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: ./data/so/val2017
    ann_file: ./data/so/annotations/instances_val2017.json
    transforms:
      type: Compose
      ops: ~ 

  shuffle: False
  batch_size: 12
  num_workers: 12
  drop_last: False
