__include__: ['/home/mkx10/workdir/DRR-detr/configs/rtdetr/rtdetr_r101vd_6x_coco.yml']
output_dir: ./output/rgq
HybridEncoder:
  use_msdca: False
  use_film: True
  use_cafe: False
RTDETRTransformer:
  use_sada: True
epoches: 72
